name = "persian-seo-website"
main = "src/index.tsx"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "SEO_DB"
database_name = "seo-db"
database_id = "dd7a9720-eb51-406e-a45a-631007e870bc"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "00000000000000000000000000000000"
preview_id = "00000000000000000000000000000000"

[assets]
directory = "./src/static"
binding = "ASSETS"
run_worker_first = true
